"""Routing: Trunk and RoutePattern.

Trunks are the egress paths from the call agent. RoutePatterns match dialed
digits and choose where to send the call — either out a Trunk (toward the
PSTN) or to an internal DirectoryNumber (translation pattern).
"""

from django.db import models
from nautobot.apps.models import PrimaryModel

from nautobot_phones.choices import TrunkTypeChoices


class Trunk(PrimaryModel):
    """An egress path from the phone system (SIP, PRI, H.323, MGCP)."""

    name = models.CharField(max_length=100)
    phone_system = models.ForeignKey(
        to="nautobot_phones.PhoneSystem",
        on_delete=models.CASCADE,
        related_name="trunks",
    )
    trunk_type = models.CharField(
        max_length=16,
        choices=TrunkTypeChoices,
    )
    destination_address = models.CharField(
        max_length=255,
        blank=True,
        help_text="FQDN or IP of the trunk far end (SIP). Blank for PRI/MGCP physical trunks.",
    )
    destination_port = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Far-end port (typically 5060 for SIP).",
    )
    css = models.ForeignKey(
        to="nautobot_phones.CallingSearchSpace",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="outbound_trunks",
        help_text="CSS used for outbound calls leaving via this trunk.",
    )
    inbound_css = models.ForeignKey(
        to="nautobot_phones.CallingSearchSpace",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="inbound_trunks",
        help_text="CSS applied to inbound calls arriving on this trunk.",
    )
    vendor_extras = models.JSONField(default=dict, blank=True)

    natural_key_field_names = ["phone_system", "name"]

    class Meta:
        """Meta options for Trunk."""

        ordering = ("phone_system", "name")
        unique_together = (("phone_system", "name"),)

    def __str__(self) -> str:
        """Display string."""
        return f"{self.phone_system.name}/{self.name}"


class RoutePattern(PrimaryModel):
    """A digit-matching pattern that routes to a Trunk or translates to a DN.

    CCM patterns support wildcards like '9.[2-9]XX[2-9]XXXXXX'. Each pattern
    targets exactly one of:
      - target_trunk: "send out this trunk" (route pattern)
      - target_dn: "translate to this DN" (translation pattern)

    The CHECK constraint enforces XOR — one and only one target. DB-level so
    a misbehaving adapter can't sneak both in.
    """

    pattern = models.CharField(
        max_length=100,
        help_text="Digit pattern (e.g. '9.[2-9]XX[2-9]XXXXXX', '+15551234XXX').",
    )
    partition = models.ForeignKey(
        to="nautobot_phones.Partition",
        on_delete=models.PROTECT,
        related_name="route_patterns",
    )
    css = models.ForeignKey(
        to="nautobot_phones.CallingSearchSpace",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="route_patterns",
        help_text="CSS applied to the leg generated by this match (intra-cluster routing).",
    )
    target_trunk = models.ForeignKey(
        to="nautobot_phones.Trunk",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="route_patterns",
    )
    target_dn = models.ForeignKey(
        to="nautobot_phones.DirectoryNumber",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="translation_patterns",
        help_text="If set, this pattern translates incoming digits to this DN.",
    )
    urgent = models.BooleanField(
        default=False,
        help_text="If true, dial as soon as the pattern matches (no inter-digit timeout).",
    )
    discard_digits = models.CharField(
        max_length=64,
        blank=True,
        help_text="Vendor-specific digit-discard rule (e.g. 'PreDot').",
    )

    natural_key_field_names = ["partition", "pattern"]

    class Meta:
        """Meta options for RoutePattern."""

        ordering = ("partition", "pattern")
        unique_together = (("partition", "pattern"),)
        constraints = [
            models.CheckConstraint(
                # XOR: exactly one of (target_trunk, target_dn) must be set.
                check=(
                    models.Q(target_trunk__isnull=False, target_dn__isnull=True)
                    | models.Q(target_trunk__isnull=True, target_dn__isnull=False)
                ),
                name="route_pattern_exactly_one_target",
            ),
        ]

    def __str__(self) -> str:
        """Display string."""
        return f"{self.partition.name}/{self.pattern}"
