# Generated by Django 5.2.13 on 2026-05-04 23:19

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0084_add_module_type_image_support'),
        ('extras', '0142_remove_scheduledjob_approval_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingSearchSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'calling search space',
                'verbose_name_plural': 'calling search spaces',
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DIDBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('start_e164', models.CharField(max_length=32)),
                ('end_e164', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='did_blocks', to='nautobot_phones.carrier')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'DID block',
                'verbose_name_plural': 'DID blocks',
                'ordering': ('carrier', 'start_e164'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('e164', models.CharField(max_length=32, unique=True)),
                ('is_special', models.BooleanField(default=False)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dids', to='nautobot_phones.didblock')),
            ],
            options={
                'verbose_name': 'DID',
                'verbose_name_plural': 'DIDs',
                'ordering': ('e164',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CSSPartitionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.PositiveIntegerField()),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='nautobot_phones.callingsearchspace')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='nautobot_phones.partition')),
            ],
            options={
                'verbose_name': 'CSS partition membership',
                'verbose_name_plural': 'CSS partition memberships',
                'ordering': ('css', 'priority'),
                'unique_together': {('css', 'partition'), ('css', 'priority')},
            },
        ),
        migrations.AddField(
            model_name='callingsearchspace',
            name='partitions',
            field=models.ManyToManyField(blank=True, related_name='calling_search_spaces', through='nautobot_phones.CSSPartitionMembership', to='nautobot_phones.partition'),
        ),
        migrations.CreateModel(
            name='PhoneSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vendor', models.CharField(max_length=32)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('delete_policy', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location')),
                ('secrets_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='extras.secretsgroup')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'phone system',
                'verbose_name_plural': 'phone systems',
                'ordering': ('name',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('device_name', models.CharField(max_length=100)),
                ('mac_address', nautobot.core.models.fields.MACAddressCharField()),
                ('model', models.CharField(blank=True, max_length=64)),
                ('registration_status', models.CharField(default='unknown', max_length=32)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='nautobot_phones.phonesystem')),
            ],
            options={
                'ordering': ('phone_system', 'device_name'),
                'unique_together': {('phone_system', 'mac_address')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='partition',
            name='phone_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='nautobot_phones.phonesystem'),
        ),
        migrations.CreateModel(
            name='DirectoryNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('extension', models.CharField(max_length=32)),
                ('alerting_name', models.CharField(blank=True, max_length=100)),
                ('voicemail_profile', models.CharField(blank=True, max_length=100)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directory_numbers', to='nautobot_phones.partition')),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_numbers', to='nautobot_phones.phonesystem')),
            ],
            options={
                'verbose_name': 'directory number',
                'verbose_name_plural': 'directory numbers',
                'ordering': ('partition', 'extension'),
                'unique_together': {('partition', 'extension')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='didblock',
            name='phone_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='did_blocks', to='nautobot_phones.phonesystem'),
        ),
        migrations.AddField(
            model_name='callingsearchspace',
            name='phone_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calling_search_spaces', to='nautobot_phones.phonesystem'),
        ),
        migrations.CreateModel(
            name='AnalogGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('protocol', models.CharField(max_length=16)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_gateways', to='nautobot_phones.phonesystem')),
            ],
            options={
                'verbose_name': 'analog gateway',
                'verbose_name_plural': 'analog gateways',
                'ordering': ('phone_system', 'name'),
                'unique_together': {('phone_system', 'name')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('trunk_type', models.CharField(max_length=16)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_trunks', to='nautobot_phones.callingsearchspace')),
                ('inbound_css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_trunks', to='nautobot_phones.callingsearchspace')),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trunks', to='nautobot_phones.phonesystem')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('phone_system', 'name'),
                'unique_together': {('phone_system', 'name')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DIDAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_id', models.UUIDField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('did', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='nautobot_phones.did')),
                ('target_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'nautobot_phones'), models.Q(('model', 'directorynumber'), ('model', 'trunk'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'DID assignment',
                'verbose_name_plural': 'DID assignments',
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='nautobot_ph_target__dfdffa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalogPort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('port_index', models.PositiveSmallIntegerField()),
                ('port_type', models.CharField(max_length=8)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='nautobot_phones.analoggateway')),
                ('directory_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analog_ports', to='nautobot_phones.directorynumber')),
            ],
            options={
                'verbose_name': 'analog port',
                'verbose_name_plural': 'analog ports',
                'ordering': ('gateway', 'port_index'),
                'unique_together': {('gateway', 'port_index')},
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('button_index', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('ring_setting', models.CharField(blank=True, max_length=32)),
                ('directory_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='nautobot_phones.directorynumber')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='nautobot_phones.phone')),
            ],
            options={
                'ordering': ('phone', 'button_index'),
                'unique_together': {('phone', 'button_index')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='partition',
            unique_together={('phone_system', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='didblock',
            unique_together={('start_e164', 'end_e164', 'carrier')},
        ),
        migrations.AlterUniqueTogether(
            name='callingsearchspace',
            unique_together={('phone_system', 'name')},
        ),
        migrations.CreateModel(
            name='RoutePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pattern', models.CharField(max_length=100)),
                ('urgent', models.BooleanField(default=False)),
                ('discard_digits', models.CharField(blank=True, max_length=64)),
                ('css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_patterns', to='nautobot_phones.callingsearchspace')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_patterns', to='nautobot_phones.partition')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('target_dn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translation_patterns', to='nautobot_phones.directorynumber')),
                ('target_trunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_patterns', to='nautobot_phones.trunk')),
            ],
            options={
                'ordering': ('partition', 'pattern'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('target_dn__isnull', True), ('target_trunk__isnull', False)), models.Q(('target_dn__isnull', False), ('target_trunk__isnull', True)), _connector='OR'), name='route_pattern_exactly_one_target')],
                'unique_together': {('partition', 'pattern')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
