# Generated by Django 5.2.13 on 2026-05-05 01:22

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('distribution_algorithm', models.CharField(default='top_down', max_length=16)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RouteGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_id', models.UUIDField()),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'route group member',
                'verbose_name_plural': 'route group members',
                'ordering': ('route_group', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='RouteList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RouteListMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'route list member',
                'verbose_name_plural': 'route list members',
                'ordering': ('route_list', 'priority'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='routepattern',
            name='route_pattern_exactly_one_target',
        ),
        migrations.AddField(
            model_name='routegroup',
            name='phone_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_groups', to='nautobot_phones.phonesystem'),
        ),
        migrations.AddField(
            model_name='routegroup',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='routegroupmember',
            name='route_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='nautobot_phones.routegroup'),
        ),
        migrations.AddField(
            model_name='routegroupmember',
            name='target_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'nautobot_phones'), models.Q(('model', 'trunk'), ('model', 'analoggateway'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='routelist',
            name='phone_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_lists', to='nautobot_phones.phonesystem'),
        ),
        migrations.AddField(
            model_name='routelist',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='routepattern',
            name='target_route_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_patterns', to='nautobot_phones.routelist'),
        ),
        migrations.AddConstraint(
            model_name='routepattern',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_dn__isnull', True), ('target_route_list__isnull', True), ('target_trunk__isnull', False)), models.Q(('target_dn__isnull', True), ('target_route_list__isnull', False), ('target_trunk__isnull', True)), models.Q(('target_dn__isnull', False), ('target_route_list__isnull', True), ('target_trunk__isnull', True)), _connector='OR'), name='route_pattern_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='routelistmember',
            name='route_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_list_memberships', to='nautobot_phones.routegroup'),
        ),
        migrations.AddField(
            model_name='routelistmember',
            name='route_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='nautobot_phones.routelist'),
        ),
        migrations.AlterUniqueTogether(
            name='routegroup',
            unique_together={('phone_system', 'name')},
        ),
        migrations.AddIndex(
            model_name='routegroupmember',
            index=models.Index(fields=['target_type', 'target_id'], name='nautobot_ph_target__81c735_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routelist',
            unique_together={('phone_system', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='routelistmember',
            unique_together={('route_list', 'priority'), ('route_list', 'route_group')},
        ),
    ]
