# Generated by Django 5.2.13 on 2026-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0002_routegroup_routegroupmember_routelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='last_registered_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
