# Generated by Django 5.2.13 on 2026-05-05 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0003_phone_last_registered_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneServiceUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('button_index', models.PositiveSmallIntegerField()),
                ('url', models.TextField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_urls', to='nautobot_phones.phone')),
            ],
            options={
                'verbose_name': 'Phone Service URL',
                'verbose_name_plural': 'Phone Service URLs',
                'ordering': ('phone', 'button_index'),
                'unique_together': {('phone', 'button_index')},
            },
        ),
        migrations.CreateModel(
            name='SpeedDial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('button_index', models.PositiveSmallIntegerField()),
                ('number', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_dials', to='nautobot_phones.phone')),
            ],
            options={
                'ordering': ('phone', 'button_index'),
                'unique_together': {('phone', 'button_index')},
            },
        ),
    ]
