# Generated by Django 5.2.13 on 2026-05-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0004_phoneserviceurl_speeddial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
