# Generated by Django 5.2.13 on 2026-05-05 05:48

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_phones', '0005_phone_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pattern', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_patterns', to='nautobot_phones.callingsearchspace')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_patterns', to='nautobot_phones.partition')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('partition', 'pattern'),
                'unique_together': {('partition', 'pattern')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
