# Generated by Django 5.2.13 on 2026-05-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0006_translationpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationpattern',
            name='block_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='called_party_transformation_mask',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='calling_party_prefix_digits',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='calling_party_transformation_mask',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='digit_discard_instruction',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='dont_wait_for_idt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='is_emergency_service_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='prefix_digits_out',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='provide_outside_dial_tone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='release_clause',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='route_class',
            field=models.CharField(blank=True, default='Default', max_length=32),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='route_next_hop_by_cgpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='urgent_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='use_calling_party_phone_mask',
            field=models.CharField(blank=True, default='Off', max_length=16),
        ),
        migrations.AddField(
            model_name='translationpattern',
            name='use_originator_css',
            field=models.BooleanField(default=False),
        ),
    ]
