# Generated by Django 5.2.13 on 2026-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0007_translationpattern_block_enable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='model',
        ),
        migrations.AddField(
            model_name='phone',
            name='aar_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='always_use_prime_line',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='phone',
            name='always_use_prime_line_for_voice',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='phone',
            name='built_in_bridge',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='phone',
            name='common_device_configuration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='common_phone_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='device_mobility_mode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='phone',
            name='device_pool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='device_security_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='dnd_option',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='phone',
            name='dnd_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='mobility_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='mtp_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='network_locale',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='phone',
            name='owner_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='packet_capture_mode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_button_template',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='privacy',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='phone',
            name='rerouting_css',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='sip_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='softkey_template',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='subscribe_css',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='user_locale',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
