# Generated by Django 5.2.13 on 2026-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0008_remove_phone_model_phone_aar_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='location',
        ),
        migrations.AddField(
            model_name='phone',
            name='ccm_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='network_location',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
