# Generated by Django 5.2.13 on 2026-05-05 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0009_remove_phone_location_phone_ccm_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='audible_mwi',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='line',
            name='busy_trigger',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='consecutive_ring_setting',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='line',
            name='max_num_calls',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='missed_call_logging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='line',
            name='mwl_policy',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='line',
            name='partition_usage',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='line',
            name='recording_flag',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='line',
            name='ring_setting_active_pickup_alert',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='line',
            name='ring_setting_idle_pickup_alert',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='BusyLampField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('button_index', models.PositiveSmallIntegerField()),
                ('destination', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('asterisk_service', models.BooleanField(default=False)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_lamp_fields', to='nautobot_phones.phone')),
            ],
            options={
                'verbose_name': 'Busy Lamp Field',
                'verbose_name_plural': 'Busy Lamp Fields',
                'ordering': ('phone', 'button_index'),
                'unique_together': {('phone', 'button_index')},
            },
        ),
    ]
