# Generated by Django 5.2.13 on 2026-05-05 20:42

import nautobot.core.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0010_line_audible_mwi_line_busy_trigger_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('phone_system', 'device_name')},
        ),
        migrations.AddField(
            model_name='phone',
            name='device_kind',
            field=models.CharField(default='sep', max_length=16),
        ),
        migrations.AlterField(
            model_name='phone',
            name='mac_address',
            field=nautobot.core.models.fields.MACAddressCharField(blank=True, null=True),
        ),
    ]
