# Generated by Django 5.2.13 on 2026-05-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0011_alter_phone_unique_together_phone_device_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='active_load',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='phone',
            name='inactive_load',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='phone',
            name='live_login_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='live_status_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='status_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
