# Generated by Django 5.2.13 on 2026-05-09 14:16

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_phones', '0013_voice_interface_customfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('call_manager_group', models.CharField(blank=True, max_length=100)),
                ('route_list_enabled', models.BooleanField(default=True)),
                ('voice_mail_usage', models.BooleanField(default=False)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_lists', to='nautobot_phones.phonesystem')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LineGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('distribution_algorithm', models.CharField(blank=True, max_length=32)),
                ('rna_reversion_timeout', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hunt_algorithm_no_answer', models.CharField(blank=True, max_length=32)),
                ('hunt_algorithm_busy', models.CharField(blank=True, max_length=32)),
                ('hunt_algorithm_not_available', models.CharField(blank=True, max_length=32)),
                ('auto_log_off_hunt', models.BooleanField(default=False)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_groups', to='nautobot_phones.phonesystem')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HuntListMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('selection_order', models.PositiveSmallIntegerField()),
                ('hunt_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='nautobot_phones.huntlist')),
                ('line_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hunt_list_memberships', to='nautobot_phones.linegroup')),
            ],
            options={
                'ordering': ('hunt_list', 'selection_order'),
                'unique_together': {('hunt_list', 'line_group')},
            },
        ),
        migrations.AddField(
            model_name='huntlist',
            name='line_groups',
            field=models.ManyToManyField(blank=True, related_name='hunt_lists', through='nautobot_phones.HuntListMember', to='nautobot_phones.linegroup'),
        ),
        migrations.CreateModel(
            name='LineGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('line_selection_order', models.PositiveSmallIntegerField()),
                ('directory_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_group_memberships', to='nautobot_phones.directorynumber')),
                ('line_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='nautobot_phones.linegroup')),
            ],
            options={
                'ordering': ('line_group', 'line_selection_order'),
                'unique_together': {('line_group', 'directory_number')},
            },
        ),
        migrations.AddField(
            model_name='linegroup',
            name='directory_numbers',
            field=models.ManyToManyField(blank=True, related_name='line_groups', through='nautobot_phones.LineGroupMember', to='nautobot_phones.directorynumber'),
        ),
        migrations.CreateModel(
            name='HuntPilot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pattern', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('alerting_name', models.CharField(blank=True, max_length=64)),
                ('max_hunt_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('forward_hunt_no_answer_destination', models.CharField(blank=True, max_length=64)),
                ('forward_hunt_busy_destination', models.CharField(blank=True, max_length=64)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('hunt_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hunt_pilots', to='nautobot_phones.huntlist')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hunt_pilots', to='nautobot_phones.partition')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('partition', 'pattern'),
                'unique_together': {('partition', 'pattern')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='huntlist',
            unique_together={('phone_system', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='linegroup',
            unique_together={('phone_system', 'name')},
        ),
    ]
