# Generated by Django 5.2.13 on 2026-05-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_phones', '0014_huntlist_linegroup_huntlistmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linegroup',
            name='hunt_algorithm_busy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='linegroup',
            name='hunt_algorithm_no_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='linegroup',
            name='hunt_algorithm_not_available',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
