# Generated by Django 5.2.13 on 2026-05-09 15:08

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('nautobot_phones', '0015_alter_linegroup_hunt_algorithm_busy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='device_pool',
        ),
        migrations.CreateModel(
            name='CallPickupGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('partition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_pickup_groups', to='nautobot_phones.partition')),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_pickup_groups', to='nautobot_phones.phonesystem')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'call pickup group',
                'verbose_name_plural': 'call pickup groups',
                'ordering': ('phone_system', 'name'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CallPickupGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('directory_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_group_through', to='nautobot_phones.directorynumber')),
                ('pickup_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_through', to='nautobot_phones.callpickupgroup')),
            ],
            options={
                'ordering': ('pickup_group', 'priority'),
                'unique_together': {('pickup_group', 'directory_number')},
            },
        ),
        migrations.AddField(
            model_name='callpickupgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='call_pickup_groups', through='nautobot_phones.CallPickupGroupMember', to='nautobot_phones.directorynumber'),
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_profiles', to='nautobot_phones.phonesystem')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'device profile',
                'verbose_name_plural': 'device profiles',
                'ordering': ('phone_system', 'name'),
                'unique_together': {('phone_system', 'name')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='phone',
            name='device_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='nautobot_phones.deviceprofile'),
        ),
        migrations.CreateModel(
            name='VoicemailProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pilot_dn', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('vendor_extras', models.JSONField(blank=True, default=dict)),
                ('phone_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voicemail_profiles', to='nautobot_phones.phonesystem')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'voicemail profile',
                'verbose_name_plural': 'voicemail profiles',
                'ordering': ('phone_system', 'name'),
                'unique_together': {('phone_system', 'name')},
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        # Drop the CharField voicemail_profile and re-add as a FK. We can't
        # do this as an in-place AlterField — the existing column is
        # VARCHAR(100) NOT NULL holding strings like "NoVoiceMail" which
        # don't coerce to a UUID FK. The next sync will repopulate the FK.
        migrations.RemoveField(
            model_name='directorynumber',
            name='voicemail_profile',
        ),
        migrations.AddField(
            model_name='directorynumber',
            name='voicemail_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_numbers', to='nautobot_phones.voicemailprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='callpickupgroup',
            unique_together={('phone_system', 'name')},
        ),
    ]
